# -*- coding: utf-8 -*-
"""2409000199[sibo patrick].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9QxIsSalA-puV5BL_CC2PUrIOfRmKwQ
"""

import requests
import json

!pip3 install requests

result = requests.get('https://api.stackexchange.com/2.3/questions?order=desc&sort=activity&site=stackoverflow')
print(result)

print(result.json())

for questions in result.json()['items']:
    if questions['answer_count'] == 0:
        print(questions['title'])
        print(questions['link'])
    else:
            print("Skipped")

            print()